export const Colors = {
  "background-secondary": "#222940",
  "primary-10": "#F1F3FC",
  "primary-50": "#E2E8FF",
  "primary-100": "#B3BEF7",
  "primary-200": "#8E9FF2",
  "primary-300": "#7388F0",
  "primary-400": "#4762E7",
  "primary-500": "#2644DB",
  "primary-600": "#102FCB",
  "primary-700": "#0320B4",
  "primary-800": "#001A9A",
  "primary-900": "#00157D",
  secondary: "#222940",
  "secondary-50": "#FCD1F4",
  "secondary-100": "#F3B1E1",
  "secondary-200": "#FA9DD9",
  "secondary-300": "#FF86CE",
  "secondary-400": "#FF63B4",
  "secondary-500": "#E753A8",
  "secondary-600": "#C84699",
  "secondary-700": "#A23A83",
  "secondary-800": "#762C64",
  "secondary-900": "#471D40",
  danger: "#D44E67",
  "danger-10": "#FFF1F4",
  "danger-50": "#FFD8E0",
  "danger-100": "#FFBCC9",
  "danger-200": "#FC91A6",
  "danger-300": "#FD5778",
  "danger-400": "#F5365C",
  "danger-500": "#DD1E44",
  "danger-600": "#BC1638",
  "danger-700": "#9A0F2A",
  "danger-800": "#810A22",
  "danger-900": "#65081B",
  "profile-sky-blue": "#80CAFF",
  "profile-mint": "#47DDE7",
  "profile-green": "#78F0C5",
  "profile-yellow-green": "#ADE353",
  "profile-purple": "#D378FE",
  "profile-red": "#FF6D88",
  "profile-orange": "#FEC078",
  "profile-yellow": "#F2ED64",
  "blue-10": "#F0F8FF",
  "blue-20": "#DBEEFF",
  "blue-30": "#C2E1FF",
  "blue-40": "#94CDFF",
  "blue-60": "#0065FF",
  "blue-70": "#0B74E5",
  "blue-90": "#074183",
  "gray-10": "#D5D9E0",
  "gray-20": "#A7B0C2",
  "gray-30": "#818DA6",
  "gray-40": "#8C8FB8",
  "gray-50": "#4C5975",
  "gray-60": "#3A4561",
  "gray-70": "#2C364F",
  "gray-80": "#222940",
  "gray-90": "#1A2033",
  "gray-100": "#141828",
  "orange-10": "#FFF5EB",
  "orange-30": "#FFD1A4",
  "orange-60": "#FC820A",
  "green-2": "#00AB5626", //RGBA - 15%
  "green-10": "#EFFFF4",
  "green-30": "#B7EFC3",
  "green-50": "#4AB57C",
  "green-60": "#00AB56",
  "red-10": "#FFF0F1",
  "red-30": "#FFB8BC",
  "red-50": "#D44E67",
  "red-60": "#FF424E",
  "yellow-50": "#D4B039",
  icon: "#2C4163",
  card: "rgba(255,255,255,0.95)",
  success: "#2DCE89",
  error: "#F5365C",
  "text-green": "#4AB57C",
  "text-red": "#D44E67",
  "text-yellow": "#FFD530",
  "text-black-very-high": "#030C1D",
  "text-black-high": "#132340",
  "text-black-medium": "#2C4163",
  "text-black-low": "#818DA6",
  "text-black-very-low": "#899BB6",
  "text-black-very-very-low": "#808089",
  "text-black-very-very-very-low": "#DCDCE3",
  "text-gray": "#d5d9e0",
  "border-gray": "#C6C6CD",
  "border-white": "#F5F5F5",
  white: "#fff",
  black: "#000",
  disabled: "#EEEEF3",
  divider: "#F5F5F5",
  transparent: "rgba(255,255,255,0)",
  "modal-backdrop": "rgba(9,18,50,0.6)",
  "card-modal-handle": "#DCDCE3",
  "setting-screen-background": "#FAFBFD",
  "camera-loading-background": "rgba(255,255,255,0.95)",
  "big-image-placeholder": "#E7E4EF",
  "chain-list-element-dragging": "rgba(242, 242, 247, 0.8)",
  "black-transparent": "rgba(0, 0, 0, 0.2)",
};

export const MainColors = {
  "primary": Colors["blue-70"],
  "background": Colors["gray-100"],
  "button-primary": Colors["blue-70"],
  "border": Colors["gray-70"],
};

export const AlertInlineColors = {
  "alert-inline-info-main": Colors["blue-70"],
  "alert-inline-info-content": Colors["gray-100"],
  "alert-inline-info-background": Colors["blue-20"],
  "alert-inline-info-border": Colors["blue-40"],
  "alert-inline-warning-main": Colors["orange-60"],
  "alert-inline-warning-content": Colors["gray-100"],
  "alert-inline-warning-background": Colors["orange-10"],
  "alert-inline-warning-border": Colors["orange-30"],
  "alert-inline-success-main": Colors["orange-60"],
  "alert-inline-success-content": Colors["gray-100"],
  "alert-inline-success-background": Colors["green-10"],
  "alert-inline-success-border": Colors["orange-30"],
  "alert-inline-error-main": Colors["red-60"],
  "alert-inline-error-content": Colors["gray-100"],
  "alert-inline-error-background": Colors["red-10"],
  "alert-inline-error-border": Colors["red-30"],
};

export const InputColors = {
  "input-active": Colors["blue-70"],
  "input-inactive": Colors["gray-60"],
  "input-error": Colors["red-50"],
  "input-value": Colors["gray-10"],
  "input-label": Colors["gray-30"],
  "input-background": Colors["gray-90"],
};

export const ToggleColors = {
  "toggle-on": "white",
  "toggle-background-on": Colors["blue-70"],
  "toggle-off": "white",
  "toggle-background-off": Colors["gray-20"],
};

export const StepViewColors = {
  "step-text-active": Colors["gray-10"],
  "step-text-inactive": Colors["gray-50"],

  "step-dot-active": Colors["blue-70"],
  "step-dot-inactive": Colors["blue-90"],

  "step-tick-active": Colors["blue-70"],
  "step-tick-inactive": Colors["blue-90"],

  "step-line-active": Colors["blue-90"],
  "step-line-inactive": Colors["gray-90"],

  "step-text-success-active": Colors["gray-10"],
  "step-text-success-inactive": Colors["gray-50"],

  "step-dot-success-active": Colors["green-50"],
  "step-dot-success-inactive": Colors["green-2"],

  "step-tick-success-active": Colors["green-50"],
  "step-tick-success-inactive": Colors["green-2"],
  
  "step-line-success-active": Colors["green-2"],
  "step-line-success-inactive": Colors["gray-90"],
};

export const AllColors = {
  ...Colors,
  ...MainColors,
  ...AlertInlineColors,
  ...InputColors,
  ...ToggleColors,
  ...StepViewColors,
  ...{
    // Belows are for the button props and may not be used as styles.
    "rect-button-default-ripple": "#CCCCCC",
    // Active opacity is 0.055 by default.
    "rect-button-default-underlay": Colors["text-black-medium"],

    "drawer-rect-button-underlay": "#F1F3FC",

    // Belows are for the button props and may not be used as styles.
    "button-secondary": Colors.secondary,
    "button-danger": Colors.danger,
    "button-primary-text-pressed": Colors["primary-500"],
    "button-secondary-text-pressed": Colors["secondary-500"],
    "button-danger-text-pressed": Colors["danger-500"],
    "button-primary-disabled": Colors["text-black-very-very-low"],
    "button-secondary-disabled": Colors["text-black-very-very-low"],
    "button-danger-disabled": Colors["text-black-very-very-low"],
    "button-primary-light": Colors["primary-50"],
    "button-secondary-light": Colors["secondary-50"],
    "button-danger-light": Colors["danger-50"],
    // For Android, note that you can't set the opacity of the ripple color.
    "button-primary-fill-ripple": Colors["primary-600"],
    "button-primary-light-ripple": Colors["primary-100"],
    "button-primary-outline-ripple": Colors["primary-100"],
    "button-secondary-fill-ripple": Colors["secondary-600"],
    "button-secondary-light-ripple": Colors["secondary-100"],
    "button-secondary-outline-ripple": Colors["secondary-100"],
    "button-danger-fill-ripple": Colors["danger-600"],
    "button-danger-light-ripple": Colors["danger-100"],
    "button-danger-outline-ripple": Colors["danger-100"],
    // For IOS, note that we just set the active opacity as 1, thus, unlike Android, it is opaque.
    "button-primary-fill-underlay": Colors["primary-500"],
    "button-primary-light-underlay": Colors["primary-100"],
    "button-primary-outline-underlay": Colors["primary-50"],
    "button-secondary-fill-underlay": Colors["secondary-500"],
    "button-secondary-light-underlay": Colors["secondary-100"],
    "button-secondary-outline-underlay": Colors["secondary-50"],
    "button-danger-fill-underlay": Colors["danger-500"],
    "button-danger-light-underlay": Colors["danger-100"],
    "button-danger-outline-underlay": Colors["danger-50"],
    "button-background-main": Colors["background-secondary"],
    // Belows are for the chip props and may not be used as styles.
    "chip-light-primary": Colors["primary-50"],
    "chip-light-secondary": Colors["secondary-50"],
    "chip-light-danger": Colors["danger-100"],

    // Belows are for the loading spinner props and may not be used as styles.
    "loading-spinner": Colors["text-black-low"],
  },
  ...{
    "heading-text": "white",
    "link-text": Colors["blue-70"],
    "rewards-text": Colors["green-50"],
    "label-text-1": Colors["gray-10"],
    "label-text-2": Colors["gray-30"],

    "card-border": Colors["gray-70"],
    "card-background-header": Colors["gray-80"],
    "card-background": Colors["gray-90"],
  },
};