#! /bin/bash -x
rm ./android/app/src/main/assets/appcenter-config.json || true
jq ".app_secret = \"$ASTRA_HUB_APP_CENTER_ANDROID_CONFIG_SECRET\"
    | .warning = \"THIS FILE IS GENERATED BY SETUP SCRIPT\"" < ./scripts/exp.appcenter-config.json \
    > ./android/app/src/main/assets/appcenter-config.json 2>/dev/null